### ISSUE TITLE
researcher "Delete Reference" does not working

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#455] opened 2016-05-13 03:58 UTC
When I add reference(interview, document) as researcher, I can not delete them again.
Here are detail steps.
1. I logged in as supervisor(jcust, jcust) and deploy new assessment(2021 China pilot) and assigned it to ionresearcher.
   2.and I logged out and logged in as ionresearcher.
   3.Went to "2021 china pilot".
   1. Added one interview.

![1](https://cloud.githubusercontent.com/assets/15853986/15237585/314c8f62-18c7-11e6-9632-af808b5de289.png)

For some reasons, I need to delete this reference.
But this button is disabled now.
 In any case, this button will be disabled, so I can not delete the wrong reference.

**Comment by alexander-elgin** [comment] 2016-05-13 06:22
The feature is disabled if there is only one reference assigned to the answer. There is no BUG.

**Closed as completed by alexander-elgin** 2016-05-13 06:22 UTC
Labels: invalid

**Comment by alexander-elgin** [comment] 2016-05-13 06:38
@ion-alecsandri In the recent time there were a lot of BUG reports from you which are not about BUGs actually but about the correct system behavior. E.g. disabled button is not a BUG, but if you click on an active button and the action is not performed that's a BUG. To save time of each other before posting a BUG report if you have doubts whether you've found a BUG or not you can send a message to me or Chris in Skype or Slack.
