### ISSUE TITLE
Existing interviewees appear on all accounts

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#258] opened 2016-03-03 15:41 UTC
Working on a researcher account (issyedwards) that's brand new, only one assignment assigned to it. Tried to add an existing interviewee when I hadn't logged an interview on this account before. When I started to type a name in the "Type name to search for existing interviewees" search bar, all interviewees referenced on other researcher accounts started to appear. @byndcivilization @ahasemann

**Comment by byndcivilization** [comment] 2016-03-03 16:45
That is correct. This is linked to #256. I'm changing the data model to provide for unique email/phone number combos.

**Comment by byndcivilization** [comment] 2016-03-03 16:47
will be in next push

**Closed as completed by byndcivilization** 2016-03-03 16:47 UTC

**Comment by isabellee** [comment] 2016-03-03 18:05
Along similar lines, if a document has previously been uploaded, the tool will sometimes automatically fill reference fields. However, I uploaded and referenced a doc as a researcher, and then uploaded the same document as a peer reviewer (so different account) and it automatically was referenced, even though the PR had never uploaded this document.

**Comment by byndcivilization** [comment] 2016-03-03 22:27
Thats by design. The document exists in the database so it shouldnt need to be entered again. We dont want to have 2 different citations for a single document.

**Comment by ahasemann** [comment] 2016-03-03 23:34
The issue with that is that it means interviewees are no longer anonymous, especially because names start showing up in the drop down menu as soon as you enter any letter that comes up in them.

**Comment by byndcivilization** [comment] 2016-03-04 04:23
yes and no. you will know they are in the system, but not what is attributed to them.

**Comment by ahasemann** [comment] 2016-03-04 06:24
Is there any way to not have that happen - at least for the interviewees (for the documents it's fine)?

**Comment by byndcivilization** [comment] 2016-03-04 07:10
This is a pretty big departure from something that has been in there for a very long time. You need some way to make sure you dont get duplicates or you will end up with junk interviewee data. Ive you are managing duplicates, then you need some sort of unique identifier. If you have a unique identifier. If you have a unique identifier then you need some way to look up to see if an id is already there. If you do that, you've lost perfect anonymity. who are you worried will see people? external reviewers? we could take interview camapbilities from that profile. The only thing i can think of is either removing uniqueness, which at that point might as well just store it all as free text and deal with a shit show of data cleaning on the back end, or maintain individual interviewee sub collections, which is way outside of the scope of what can be done basically tomorrow.

**Comment by ahasemann** [comment] 2016-03-04 07:23
What I am worried about is somebody other than the person inputting the interviewee information seeing it (even - that could be the researcher/ external reviewers if it's the peer reviewer or the peer reviewer/ external reviewers if its the researcher. Even if it's just their name this means interviewees are not anonymous. So if that is not possible, we will have to work around it and not use the tool to record interview data at least for people that want to be anonymous, I think?

**Comment by byndcivilization** [comment] 2016-03-04 07:38
Maybe an anonymous record and a free text files on the reference in such cases to record contact details? That field could be set to show only to admin. Catch is that it would have to be added each time the interview is cited

**Comment by ahasemann** [comment] 2016-03-04 08:00
So consultants could indicate in the tool if they want the interviewee to be anonymous and the recording function would be different then?

**Comment by ahasemann** [comment] 2016-03-04 08:03
Wait, sorry, all records would be anonymous and the admin would then add the interviewee info afterwards?

**Comment by byndcivilization** [comment] 2016-03-04 12:07
Two levels of anonymity. All things are anonymous in that quote won't show name. Some are extra anonymous in that they are attributed to an "anonymous" interview. In these cases there would be an extra free text field sort of like pageS. This is where the consultant would add contact details. 

Otherwise this whole model is broken and I see no way out save just making these completely free text fields.

**Comment by ahasemann** [comment] 2016-03-04 12:15
Ok that makes sense. How would the consultant indicate which ones should be extra anonymous?

**Comment by byndcivilization** [comment] 2016-03-04 12:24
Those would be tagged to this anonymous interviewee profile. It doesn't exist yet
