### ISSUE TITLE
assessment tagging to admins - not visible/ apparent how this can be done

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#289] opened 2016-03-07 11:48 UTC

**Comment by byndcivilization** [comment] 2016-03-07 15:05
Not implemented yet as it was a suuuuuuuper late feature request. Trying to get there. will let you know when its done.

**Comment by byndcivilization** [comment] 2016-03-07 15:52
duplicate of #198

**Closed as completed by byndcivilization** 2016-03-07 15:52 UTC
Labels: enhancement, workflow

**Comment by ahasemann** [comment] 2016-03-07 16:27
Ok
