### ISSUE TITLE
Assessments skipping trial stage when starting peer review

### ISSUE THREAD

**Issue by sgautvik** [NRGI/rgi-assessment-tool#534] opened 2016-10-05 08:32 UTC
For the two most recent peer reviews I have started, the assessment has jumped straight to the full assessment once I assign a peer reviewer. When I have gone to check the assessments they have been marked as submitted/resubmitted though the peer reviewer has not done anything on the assessment. 

This has now happened for Uzbekistan, Papua New Guinea, Guatemala and Ecuador, and Malaysia has also experienced the assessment being marked as resubmitted without the researcher actually submitting.

@alexander-elgin @DianaHartmann

**Comment by alexander-elgin** [comment] 2016-10-05 10:33
@sgautvik What are the assessments where the reviewers started the full assessment without the trial one?

**Comment by sgautvik** [comment] 2016-10-05 10:36
@alexander-elgin Uzbekistan and Papua New Guinea this week, and previously also Ghana (hydrocarbons) and Mongolia have all skipped the trial assessment.

**Comment by alexander-elgin** [comment] 2016-10-05 12:38
The issue was encountered in the following assessments
http://rgi.nrgi-assessment.org/admin/assessments-admin/UZ-2016-HY
http://rgi.nrgi-assessment.org/admin/assessments-admin/PG-2016-MI

http://rgi.nrgi-assessment.org/admin/assessments-admin/GH-2016-HY
http://rgi.nrgi-assessment.org/admin/assessments-admin/MN-2016-MI

**Comment by alexander-elgin** [comment] 2016-10-06 10:13
I still cannot reproduce the issue. @sgautvik Was there anything special done with the assessments e.g. manual change of the assessment status, reassign the researcher / reviewer?

**Comment by sgautvik** [comment] 2016-10-06 11:48
@alexander-elgin Nothing special was done. The issue occurred when the peer reviewer was assigned to the assessments for the first time, to start the trial. None of the assessments have had reviewers reassigned. When the peer reviewers have informed us that there is an issue, the assessment status has been manually changed to the trial stage.

Would it be helpful for you to know when we are next going to assign a peer reviewer to start the trial?

**Comment by alexander-elgin** [comment] 2016-10-07 03:45
@sgautvik OK, let's check it because I still cannot reproduce the issue. Each assessment history has from 1300 to 2700 log records. Based on `UZ-2016-HY` logs I noticed that the reviewer was assigned right before the assessment was passed to him.
While the researcher is working on the full assessment the reviewer can see the full assessment answers. However when the reviewer starts the trial assessment the answer of the full assessment become unavailable for him.
I tried to changed the assessment status manually, I left reviewer unassigned, I reassigned the reviewers and researchers but the result is always the same: the full assessment answers are hidden for the peer reviewer on trial assessment stage.

**Comment by sgautvik** [comment] 2016-10-11 09:05
@alexander-elgin I just assigned a peer reviewer for the following assessment: UA-2016-HY (Ukraine). I have passed the assessment to him, opened the assessment to check, and I can see the full assessment as it was when I had approved all the questions of the researcher.

![image](https://cloud.githubusercontent.com/assets/19529874/19264792/27c0c356-8f9a-11e6-8c79-aa2442ad0e33.png)

**Comment by alexander-elgin** [comment] 2016-10-27 07:29
@sgautvik The supervisor can browse the full assessment because the researcher submitted the full assessment. But for the reviewer the trial assessment available only.

**Closed as completed by alexander-elgin** 2016-10-27 07:29 UTC
Labels: bug, cant recreate
