### ISSUE TITLE
Can't type into reference boxes

### ISSUE THREAD

**Issue by HumairaP** [NRGI/rgi-assessment-tool#174] opened 2016-02-24 15:59 UTC
[can't type in boxes.docx](https://github.com/NRGI/rgi-assessment-tool/files/144915/can.t.type.in.boxes.docx)

**Comment by HumairaP** [comment] 2016-02-24 16:00
Can't type into title, select type, year, publisher and url boxes

**Comment by ahasemann** [comment] 2016-02-25 12:08
Today this initially worked for me for the first reference I uploaded, but then I had the same issue

**Comment by ahasemann** [comment] 2016-02-25 14:30
It seems to happen after you've deleted a reference and then want to add a new one on that same question page

**Comment by byndcivilization** [comment] 2016-02-25 22:55
okay @ahasemann and @HumairaP  im going to deprioritize this for now. i change the way we deal with deletions (we dont strictly delete them now so much as hide them) which may have taken care of this bug accidentally. Let me know if it persists after i redo things tomorrow.

**Comment by ahasemann** [comment] 2016-02-29 10:33
Have the same issue again, this time it was not after deleting anything. I can type into the page number & comments fields and select the date, but cannot type into any of the other fields

**Comment by byndcivilization** [comment] 2016-02-29 11:57
Update hasn't been pushed yet.

**Comment by ahasemann** [comment] 2016-02-29 16:06
Still happening

**Comment by byndcivilization** [comment] 2016-02-29 18:52
@ahasemann @HumairaP I cant recreate this. can you tell me exact steps?

**Comment by ahasemann** [comment] 2016-02-29 20:04
I am now at home and using my own computer, cannot recreate either, but encountering a different issue (see #220). Will check again in work tomorrow

**Comment by ahasemann** [comment] 2016-03-01 18:05
It happens when you want to create a new document, last night and this morning it worked for us, but now it is not working again - in either the researcher or peer reviewer view

**Comment by byndcivilization** [comment] 2016-03-01 19:43
I still cant replicate this. is there a specific document type that is causing this? is this a local file or a url based upload? can you send me the doc you tried to upload?

**Comment by ahasemann** [comment] 2016-03-01 19:52
It is now working again (so this is coming on and off again for all of us). The others have gone home, I'll check with them tomorrow what documents they were trying to upload. I was trying to upload: 
[Global-Peace-Index-Report-2015_0.pdf](https://github.com/NRGI/rgi-assessment-tool/files/153503/Global-Peace-Index-Report-2015_0.pdf)
![Uploading world-commodities-map_536bebb20436a.png…]()

**Comment by byndcivilization** [comment] 2016-03-01 19:56
and this worked and then didnt work? The only thin I can think of is that these might have come right after the tool was updated. Basically updating the tool kills the server and creates a new one. This means that all users are logged off. However, since some of the site would be cached on the users computer, they can still navigate and interact with a very buggy site that is not connected to the db. During deployment the solution is just to do once a week code pushes late sunday night. While we're in testing mode, ill try to be better about signalling on the slack channel with an @channel updating message.

**Comment by ahasemann** [comment] 2016-03-01 19:59
Yes, it works and doesn't work. It's very possible that it's connected to tool updates, today it did only start at the end of the day and was working fine yesterday evening/ this morning. So we need to make sure we log off the site and log  in again after an update?

**Comment by byndcivilization** [comment] 2016-03-01 21:49
Okay lets deprioritise  for now and keep an eye out

**Comment by byndcivilization** [comment] 2016-03-02 23:04
I'm closing this. open if it reappears.

**Comment by ahasemann** [comment] 2016-03-07 16:31
@byndcivilization Was walking Jim through the tool and the exact same thing was happening again

**Comment by ahasemann** [comment] 2016-03-07 16:32
Also happened to @isabellee today and last week

**Comment by byndcivilization** [comment] 2016-03-07 16:43
@ahasemann did this happen when the tool was being updated or crashed?

**Comment by jimc33** [comment] 2016-03-07 16:49
Happened/reproduced a few times spread out by 1 hour so don't think it was when either being crashed or updated.

**Comment by ahasemann** [comment] 2016-03-07 16:51
Also, we were logging in and out continuously, so don't think this was a cache issue

**Comment by byndcivilization** [comment] 2016-03-07 17:03
next time it happens leave it up and get me directly on a slack pm. I can trouble shoot browser and server logs

**Comment by ahasemann** [comment] 2016-03-07 17:11
Ok

**Closed as completed** 2016-03-08 19:13 UTC
Labels: bug, UI
