### ISSUE TITLE
Assign Assessment to Supervisor(s) - not working with one supervisor

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#418] opened 2016-04-28 15:42 UTC
log in as admin, go to admin assessment.
and here ,let's  assign supervisor.
If we add supervisor, there will more than one supervisor.
We click "Assign supervisor(s)" button.
At this time,if there exists supervisors we added, then it should says "already supervisor exist!" as notice message.
But it does nothing.
![1](https://cloud.githubusercontent.com/assets/15853986/14891795/1c992228-0d60-11e6-8810-96f261cfae60.png)

and if there is one supervisor, then we change that supervisor.
This also does not working.

**Comment by byndcivilization** [comment] 2016-04-28 18:22
@ion-alecsandri I think you're trying to say that there is no confirmation when a supervisor is removed?

**Comment by alexander-elgin** [comment] 2016-04-29 03:03
I don't understand what the issue is. @ion-alecsandri can you explain, please? As I see on the picture you attached you selected 2 different supervisors (Ion Alecsandri and Ion asdf).

**Comment by alexander-elgin** [comment] 2016-04-29 03:11
@ion-alecsandri Also can you write the test cases a bit more structured, please? E.g. like [Gherkin](https://github.com/cucumber/cucumber/wiki/Gherkin) suggests:

### I perform the following actions
- step 1
- step 2
- step 3

### The actual result / behavior is

description

### The expected result / behavior should be

description

**Comment by ion-alecsandri** [comment] 2016-04-29 03:30
1.log in with "user: jcust, Pw:  jcust".
2.go to  assessment admin
3. Click assign drop down, and then select Supervisors.
![screenshot from 2016-04-29 04 07 44](https://cloud.githubusercontent.com/assets/15853986/14907541/3b282934-0dc2-11e6-91d2-dd138fd47ebc.png)
4.add superuser
then there will be   3 supervisors like above screenshot.
5.And click "Assign supervisors" button.
then it will work well.(it will says "assessment updated")
And again, click assign drop down, select Superviosrs.
it will display 3 supervisors.
Delete Jim cust.
Then, there will be 2 supervisors Ion alecsandri, Ion asdf.
And click  "Assign supervisors" button.
![screenshot from 2016-04-29 04 20 43](https://cloud.githubusercontent.com/assets/15853986/14907598/0f52136e-0dc3-11e6-8e11-0e61a4ff0fb5.png)

Then it will do nothing, but if you refresh page, and go to here again, you will see 2 supervisors ion alecsandri and ion asdf.

**Comment by alexander-elgin** [comment] 2016-04-29 03:42
Indeed
- The dialog is not closed
- There is no confirmation message
- There is an error message in the browser console

The same issue is for external reviewers as well.

**Comment by ion-alecsandri** [comment] 2016-04-29 03:43
yes

**Comment by alexander-elgin** [comment] 2016-04-29 03:59
fixed in https://github.com/NRGI/rgi-assessment-tool/pull/421

**Closed as completed by alexander-elgin** 2016-04-29 03:59 UTC
Labels: bug, UI
